#-------------------------------------
# to run on local : http://[IP address of service from get all command]:8080
#-------------------------------------
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-flask # name of deployment
spec:
  selector:
    matchLabels:
      run: my-flask
  replicas: 2 # how many pods replications
  template:
    metadata:
      labels:
        run: my-flask
    spec:
      containers:
      - name: my-flask
        image: tomday/flask-hello:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: my-flask
    labels:
      run: my-flask
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 5000
      protocol: TCP
    selector:
      run: my-flask
