apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flask-deployment # name of deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1 # how many pods replicas
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: tomday/flask-hello:latest
        ports:
        - containerPort: 5000