apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flask-deployment # name of deployment
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1 # how many pods replicas
  template:
    metadata:
      labels:
        app: flask-template
    spec:
      containers:
      - name: flask-container
        image: tomday/flask-hello:latest
        ports:
        - containerPort: 5000


kind: Service 
apiVersion: v1 
metadata:
  name: flask-service 
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster 
  type: NodePort

  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    app: flask-app

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - nodePort: 30163
      port: 6000 
      targetPort: 8080