#-------------------------------------
# to run on local host : http://[IP address of service from get all command]:8080
# to run from web, attach external IP: (didnt try yet)
# microk8s kubectl patch svc pmy-flask -p '{"spec":{"externalIPs":["192.168.0.194"]}}'
#-------------------------------------
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-flask # name of deployment
spec:
  selector:
    matchLabels:
      run: my-flask
  replicas: 2 # how many pods replications
  template:
    metadata:
      labels:
        run: my-flask
    spec:
      containers:
      - name: my-flask
        image: tomday/flask-hello:latest
        ports:
        - containerPort: 5000 #internal port
---
apiVersion: v1
kind: Service
metadata:
    name: my-flask
    labels:
      run: my-flask
spec:
    type: LoadBalancer
    ports:
    - port: 8080 #16443 # external port
      targetPort: 5000 # internal port
      protocol: TCP
    selector:
      run: my-flask
    externalIPs:
      - 13.93.35.234  
