apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flask-deployment # name of deployment
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1 # how many pods replicas
  template:
    metadata:
      labels:
        app: flask-template
    spec:
      containers:
      - name: flask-container
        image: tomday/flask-hello:latest
        ports:
        - containerPort: 5000


apiVersion: v1
kind: Service
metadata:
    name: my-flask-service
    labels:
      run: my-flask-service
spec:
    ports:
    - port: 5000
      protocol: TCP
    selector:
      run: flask-app
