apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-flask # name of deployment
spec:
  selector:
    matchLabels:
      run: my-flask
  replicas: 1 # how many pods replicas
  template:
    metadata:
      labels:
        run: my-flask
    spec:
      containers:
      - name: my-flask
        image: tomday/flask-hello:latest
        ports:
        - containerPort: 5000


apiVersion: v1
kind: Service
metadata:
    name: my-flask
    labels:
      run: my-flask
spec:
    ports:
    - port: 5000
      protocol: TCP
    selector:
      run: my-flask
